defmodule CredenceRules.Pattern.SchemaWithBusinessLogic do
  @moduledoc """
  Architecture rule: an Ecto schema module (one that has `use
  Ecto.Schema` + a `schema do ... end` block) should be **data**, not
  **behaviour**. Functions beyond `changeset/1,2`, `__schema__/1`,
  and trivial accessors don't belong on the schema — they belong in
  a context module that takes the schema as data.

  LLMs love to write `def calculate_score(user)`, `def can_publish?(user)`,
  and `def send_welcome(user)` inside `User` because it reads like the
  OO `User` class. In Elixir, those functions create a god-module: the
  schema becomes coupled to every business policy, and every reader of
  `User` has to scroll past the policies to find the schema definition.

  ## Bad

      defmodule MyApp.User do
        use Ecto.Schema

        schema "users" do
          field :name, :string
          field :email, :string
          timestamps()
        end

        def changeset(user, attrs) do
          user
          |> Ecto.Changeset.cast(attrs, [:name, :email])
          |> Ecto.Changeset.validate_required([:name, :email])
        end

        def calculate_score(user) do
          # ...business logic
        end

        def can_publish?(user) do
          # ...permissions logic
        end

        def send_welcome(user) do
          # ...side effect: enqueues an Oban job, etc.
        end
      end

  ## Good — schema is data, logic lives in a context

      defmodule MyApp.User do
        use Ecto.Schema

        schema "users" do
          field :name, :string
          field :email, :string
          timestamps()
        end

        def changeset(user, attrs), do: ...
      end

      defmodule MyApp.Accounts do
        def calculate_score(%User{} = user), do: ...
        def can_publish?(%User{} = user), do: ...
        def send_welcome(%User{} = user), do: ...
      end

  ## Detection

  A module is recognised as a schema when its body contains:

  - `use Ecto.Schema`, AND
  - A top-level `schema "name" do ... end` (or `embedded_schema`,
    `schema_prefix`, etc.)

  Allowed function names (these are the schema's natural interface,
  not business logic):

  - `changeset/1`, `changeset/2`, `changeset/3`
  - Any `*_changeset/_` (e.g. `create_changeset`, `update_changeset`,
    `password_changeset`)
  - `new/0`, `new/1` (struct constructors that delegate to changeset)
  - `__schema__/1` (auto-generated by Ecto)

  Any other public `def` flags the schema. `defp` (private) functions
  are allowed regardless — they're internal to changeset construction.

  ## Why advisory

  Single-table-inheritance schemas, embedded value-objects, and very
  small Phoenix apps occasionally put one or two helpers on the
  schema deliberately. Treat findings as "should this live in a
  context?" — not a hard architectural cap.
  """

  use CredenceRules.Rule

  alias CredenceRules.AstKeyword

  @hint """
  Move the business logic into the context module:

      # Before — logic inside the schema
      defmodule MyApp.User do
        use Ecto.Schema
        schema "users", do: ...

        def changeset(user, attrs), do: ...
        def send_welcome_email(user), do: Mailer.deliver(...)
        def calculate_score(user), do: ...
      end

      # After
      defmodule MyApp.User do
        use Ecto.Schema
        schema "users", do: ...
        def changeset(user, attrs), do: ...
      end

      defmodule MyApp.Accounts do
        def send_welcome_email(user), do: Mailer.deliver(...)
        def calculate_score(user), do: ...
      end

  Schemas are data + the cast/validation contract. Anything beyond
  changeset/N and trivial field accessors goes in the context.
  """

  @carve_outs [
    "`changeset/_` functions (any arity) — schema's data-contract API, allowed.",
    "Trivial accessors like `def full_name(%__MODULE__{first: f, last: l}), do: f <> \" \" <> l` — pure transformations of the struct's own fields, often a judgment call. Rule flags conservatively; accept the finding if you want them in a Presenter.",
    "Schema-as-validator pattern where the changeset itself encodes complex business rules — those rules legitimately live near the data shape."
  ]

  @impl true
  def priority, do: 440

  @impl true
  def check(ast, _opts) do
    {_ast, issues} =
      Macro.prewalk(ast, [], fn
        {:defmodule, meta, [_alias, kw]} = node, acc when is_list(kw) ->
          case AstKeyword.get(kw, :do) do
            nil -> {node, acc}
            body -> {node, check_module(body, meta) ++ acc}
          end

        node, acc ->
          {node, acc}
      end)

    Enum.reverse(issues)
  end

  defp check_module(body, meta) do
    if schema_module?(body) do
      offenders = collect_business_logic_defs(body)

      case offenders do
        [] -> []
        names -> [build_issue(meta, names)]
      end
    else
      []
    end
  end

  defp schema_module?(body) do
    statements = top_level_statements(body)
    Enum.any?(statements, &uses_ecto_schema?/1) and Enum.any?(statements, &schema_block?/1)
  end

  defp top_level_statements({:__block__, _, list}), do: list
  defp top_level_statements(single), do: [single]

  defp uses_ecto_schema?({:use, _, [{:__aliases__, _, [:Ecto, :Schema]}]}), do: true
  defp uses_ecto_schema?({:use, _, [{:__aliases__, _, [:Ecto, :Schema]}, _opts]}), do: true
  defp uses_ecto_schema?(_), do: false

  # Recognises `schema "..." do ... end`, `embedded_schema do ... end`,
  # and a couple of common variants.
  defp schema_block?({form, _, _})
       when form in [:schema, :embedded_schema, :typed_schema, :typed_embedded_schema],
       do: true

  defp schema_block?(_), do: false

  defp collect_business_logic_defs(body) do
    body
    |> top_level_statements()
    |> Enum.flat_map(&public_def_name_arity/1)
    |> Enum.reject(&allowed_name?/1)
    |> Enum.map(fn {name, arity} -> "#{name}/#{arity}" end)
  end

  defp public_def_name_arity({:def, _, [head, _kw]}) do
    case def_head(head) do
      {name, arity} -> [{name, arity}]
      _ -> []
    end
  end

  defp public_def_name_arity(_), do: []

  defp def_head({:when, _, [inner, _guard]}), do: def_head(inner)

  defp def_head({name, _meta, params}) when is_atom(name) and is_list(params),
    do: {name, length(params)}

  defp def_head({name, _meta, nil}) when is_atom(name), do: {name, 0}
  defp def_head(_), do: nil

  defp allowed_name?({:changeset, arity}) when arity in [1, 2, 3], do: true
  defp allowed_name?({:new, arity}) when arity in [0, 1], do: true
  defp allowed_name?({:__schema__, 1}), do: true

  defp allowed_name?({name, _arity}) when is_atom(name) do
    str = Atom.to_string(name)
    String.ends_with?(str, "_changeset") or String.ends_with?(str, "changeset")
  end

  defp allowed_name?(_), do: false

  defp build_issue(meta, names) do
    {first_three, rest} = Enum.split(names, 3)
    sample = Enum.join(first_three, ", ")
    extra = if rest == [], do: "", else: " (+#{length(rest)} more)"

    %Issue{
      rule: :schema_with_business_logic,
      message:
        "Ecto schema module defines public functions beyond `changeset/_` and " <>
          "trivial accessors: #{sample}#{extra}. Schemas should be data; business " <>
          "logic belongs in a context module that takes the schema as `%Schema{}` " <>
          "data. LLMs default to OO-style entity methods (`User.calculate_score/1`); " <>
          "move them to `Accounts.calculate_score/1`.",
      meta: %{line: Keyword.get(meta, :line), functions: names}
    }
  end
end
